env:
  global:
    - MAKEFLAGS="-j 2"

before_install:
  - sudo apt-get install -y libmpfr-dev libboost-all-dev
  - export TRAVIS_WORKER_MAX_LOG_LENGTH=40000000
install: make --no-print-directory
language: cpp
