env:
  global:
    - MAKEFLAGS="-j2 --no-print-directory -s"

before_install:
  - sudo apt-get install -y libmpfr-dev libboost-all-dev
  - export TRAVIS_WORKER_MAX_LOG_LENGTH=40000000
install: make >/dev/null
language: cpp
